/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReservedRouteImport } from './routes/reserved'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as PackFamilyRouteImport } from './routes/pack-family'
import { Route as LitterRouteImport } from './routes/litter'
import { Route as HealthGuaranteeRouteImport } from './routes/health-guarantee'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PuppiesSlugRouteImport } from './routes/puppies/$slug'
import { Route as PortalOnboardingRouteImport } from './routes/portal/onboarding'
import { Route as PortalMeRouteImport } from './routes/portal/me'
import { Route as PortalDashboardRouteImport } from './routes/portal/dashboard'
import { Route as PortalAdminRouteImport } from './routes/portal/admin'
import { Route as ApprovedTokenRouteImport } from './routes/approved/$token'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservedRoute = ReservedRouteImport.update({
  id: '/reserved',
  path: '/reserved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const PackFamilyRoute = PackFamilyRouteImport.update({
  id: '/pack-family',
  path: '/pack-family',
  getParentRoute: () => rootRouteImport,
} as any)
const LitterRoute = LitterRouteImport.update({
  id: '/litter',
  path: '/litter',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthGuaranteeRoute = HealthGuaranteeRouteImport.update({
  id: '/health-guarantee',
  path: '/health-guarantee',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuppiesSlugRoute = PuppiesSlugRouteImport.update({
  id: '/puppies/$slug',
  path: '/puppies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalOnboardingRoute = PortalOnboardingRouteImport.update({
  id: '/portal/onboarding',
  path: '/portal/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalMeRoute = PortalMeRouteImport.update({
  id: '/portal/me',
  path: '/portal/me',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/portal/dashboard',
  path: '/portal/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/portal/admin',
  path: '/portal/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovedTokenRoute = ApprovedTokenRouteImport.update({
  id: '/approved/$token',
  path: '/approved/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/health-guarantee': typeof HealthGuaranteeRoute
  '/litter': typeof LitterRoute
  '/pack-family': typeof PackFamilyRoute
  '/parents': typeof ParentsRoute
  '/process': typeof ProcessRoute
  '/reserved': typeof ReservedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/waitlist': typeof WaitlistRoute
  '/approved/$token': typeof ApprovedTokenRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/me': typeof PortalMeRoute
  '/portal/onboarding': typeof PortalOnboardingRoute
  '/puppies/$slug': typeof PuppiesSlugRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/health-guarantee': typeof HealthGuaranteeRoute
  '/litter': typeof LitterRoute
  '/pack-family': typeof PackFamilyRoute
  '/parents': typeof ParentsRoute
  '/process': typeof ProcessRoute
  '/reserved': typeof ReservedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/waitlist': typeof WaitlistRoute
  '/approved/$token': typeof ApprovedTokenRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/me': typeof PortalMeRoute
  '/portal/onboarding': typeof PortalOnboardingRoute
  '/puppies/$slug': typeof PuppiesSlugRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/health-guarantee': typeof HealthGuaranteeRoute
  '/litter': typeof LitterRoute
  '/pack-family': typeof PackFamilyRoute
  '/parents': typeof ParentsRoute
  '/process': typeof ProcessRoute
  '/reserved': typeof ReservedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/waitlist': typeof WaitlistRoute
  '/approved/$token': typeof ApprovedTokenRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/me': typeof PortalMeRoute
  '/portal/onboarding': typeof PortalOnboardingRoute
  '/puppies/$slug': typeof PuppiesSlugRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/faq'
    | '/get-started'
    | '/health-guarantee'
    | '/litter'
    | '/pack-family'
    | '/parents'
    | '/process'
    | '/reserved'
    | '/reset-password'
    | '/sitemap.xml'
    | '/thank-you'
    | '/waitlist'
    | '/approved/$token'
    | '/portal/admin'
    | '/portal/dashboard'
    | '/portal/me'
    | '/portal/onboarding'
    | '/puppies/$slug'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/faq'
    | '/get-started'
    | '/health-guarantee'
    | '/litter'
    | '/pack-family'
    | '/parents'
    | '/process'
    | '/reserved'
    | '/reset-password'
    | '/sitemap.xml'
    | '/thank-you'
    | '/waitlist'
    | '/approved/$token'
    | '/portal/admin'
    | '/portal/dashboard'
    | '/portal/me'
    | '/portal/onboarding'
    | '/puppies/$slug'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/faq'
    | '/get-started'
    | '/health-guarantee'
    | '/litter'
    | '/pack-family'
    | '/parents'
    | '/process'
    | '/reserved'
    | '/reset-password'
    | '/sitemap.xml'
    | '/thank-you'
    | '/waitlist'
    | '/approved/$token'
    | '/portal/admin'
    | '/portal/dashboard'
    | '/portal/me'
    | '/portal/onboarding'
    | '/puppies/$slug'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  FaqRoute: typeof FaqRoute
  GetStartedRoute: typeof GetStartedRoute
  HealthGuaranteeRoute: typeof HealthGuaranteeRoute
  LitterRoute: typeof LitterRoute
  PackFamilyRoute: typeof PackFamilyRoute
  ParentsRoute: typeof ParentsRoute
  ProcessRoute: typeof ProcessRoute
  ReservedRoute: typeof ReservedRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThankYouRoute: typeof ThankYouRoute
  WaitlistRoute: typeof WaitlistRoute
  ApprovedTokenRoute: typeof ApprovedTokenRoute
  PortalAdminRoute: typeof PortalAdminRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalMeRoute: typeof PortalMeRoute
  PortalOnboardingRoute: typeof PortalOnboardingRoute
  PuppiesSlugRoute: typeof PuppiesSlugRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserved': {
      id: '/reserved'
      path: '/reserved'
      fullPath: '/reserved'
      preLoaderRoute: typeof ReservedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack-family': {
      id: '/pack-family'
      path: '/pack-family'
      fullPath: '/pack-family'
      preLoaderRoute: typeof PackFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/litter': {
      id: '/litter'
      path: '/litter'
      fullPath: '/litter'
      preLoaderRoute: typeof LitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-guarantee': {
      id: '/health-guarantee'
      path: '/health-guarantee'
      fullPath: '/health-guarantee'
      preLoaderRoute: typeof HealthGuaranteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puppies/$slug': {
      id: '/puppies/$slug'
      path: '/puppies/$slug'
      fullPath: '/puppies/$slug'
      preLoaderRoute: typeof PuppiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/onboarding': {
      id: '/portal/onboarding'
      path: '/portal/onboarding'
      fullPath: '/portal/onboarding'
      preLoaderRoute: typeof PortalOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/me': {
      id: '/portal/me'
      path: '/portal/me'
      fullPath: '/portal/me'
      preLoaderRoute: typeof PortalMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/portal/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/admin': {
      id: '/portal/admin'
      path: '/portal/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approved/$token': {
      id: '/approved/$token'
      path: '/approved/$token'
      fullPath: '/approved/$token'
      preLoaderRoute: typeof ApprovedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  FaqRoute: FaqRoute,
  GetStartedRoute: GetStartedRoute,
  HealthGuaranteeRoute: HealthGuaranteeRoute,
  LitterRoute: LitterRoute,
  PackFamilyRoute: PackFamilyRoute,
  ParentsRoute: ParentsRoute,
  ProcessRoute: ProcessRoute,
  ReservedRoute: ReservedRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThankYouRoute: ThankYouRoute,
  WaitlistRoute: WaitlistRoute,
  ApprovedTokenRoute: ApprovedTokenRoute,
  PortalAdminRoute: PortalAdminRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalMeRoute: PortalMeRoute,
  PortalOnboardingRoute: PortalOnboardingRoute,
  PuppiesSlugRoute: PuppiesSlugRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
